export const ERROR_CODES = {
  // Auth
  INVALID_CREDENTIALS: 'AUTH_001',
  ACCOUNT_LOCKED: 'AUTH_002',
  ACCOUNT_INACTIVE: 'AUTH_003',
  TOKEN_EXPIRED: 'AUTH_004',
  TWO_FACTOR_REQUIRED: 'AUTH_005',

  // Duplicates
  DUPLICATE_EMAIL: 'DUP_001',
  DUPLICATE_NIC: 'DUP_002',
  DUPLICATE_PHONE: 'DUP_003',
  DUPLICATE_LICENSE: 'DUP_004',
  DUPLICATE_PLATE: 'DUP_005',
  DUPLICATE_CHASSIS: 'DUP_006',
  DUPLICATE_TEST_CODE: 'DUP_007',
  DUPLICATE_BRANCH_CODE: 'DUP_008',
  PATIENT_DUPLICATE_WARNING: 'DUP_009',

  // Job
  INVALID_STATUS_TRANSITION: 'JOB_001',
  NO_BRANCH_AVAILABLE: 'JOB_002',
  JOB_ALREADY_ASSIGNED: 'JOB_003',
  REASON_REQUIRED: 'JOB_004',

  // Branch
  BRANCH_OFFLINE: 'BR_001',
  BRANCH_HAS_ACTIVE_JOBS: 'BR_002',
  INVALID_LAB_ASSIGNMENT: 'BR_003',

  // General
  NOT_FOUND: 'GEN_001',
  FORBIDDEN: 'GEN_002',
  VALIDATION_FAILED: 'GEN_003',
} as const;