export enum JobStatus {
  PENDING = 'pending',
  QUEUED = 'queued',
  ACCEPTED = 'accepted',
  ALLOCATED = 'allocated',
  DISPATCHED = 'dispatched',
  EN_ROUTE = 'en_route',
  ARRIVED = 'arrived',
  COLLECTING = 'collecting',
  COLLECTED = 'collected',
  RETURNING = 'returning',
  AT_CENTER = 'at_center',
  SENT_TO_LAB = 'sent_to_lab',
  LAB_RECEIVED = 'lab_received',
  PROCESSING = 'processing',
  REPORT_READY = 'report_ready',
  REPORT_REVIEWED = 'report_reviewed',
  COMPLETED = 'completed',
  FAILED = 'failed',
  REJECTED = 'rejected',
  CANCELLED = 'cancelled',
  PAYMENT_COLLECTED = 'payment_collected',
  HARD_COPY_READY = 'hard_copy_ready',
}